name: tsigo.github.io
description: Blog posts by Robert Speicher (tsigo)
url: http://tsigo.github.io/
markdown: redcarpet
markdown_ext: markdown,mkd,md
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
